version: "3.9"

services: 


  cursos_service:
    restart: always
    build:
      context: ../courses_ms
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    container_name: servicio_cursos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    


  getway_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: getway_service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth_service:
    restart: always
    build:
      context: ../auth_ms
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: auth_service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  personalinfo_service:
    restart: always
    build: 
      context: ../personal_info_ms
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: personal_info
    extra_hosts:
      - "host.docker.internal:host-gateway"

  financial_service:
    restart: always
    build: 
      context: ../financial_info_ms
      dockerfile: Dockerfile
    ports:
      - 5135:80
    container_name: financial_info_ms
    extra_hosts:
      - "host.docker.internal:host-gateway"

  academic_service:
    restart: always
    build: 
      context: ../academic_info_ms
      dockerfile: Dockerfile
    ports:
      - 9040:9040
    container_name: academic_info_ms
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq3:
    container_name: "rabbit"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=grupo-2b
      - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # info_service:
  #   restart: always
  #   build:
  #     context: ./personal_info_ms-master
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   container_name: servicio_info
